### ISSUE TITLE
20230423 review

### ISSUE THREAD

**Issue by init** [p1xelse/VK-Education-Highload-Twitch#1]
Замечания:

1. [x] при DAU=31M запросов навигации по контенту всего 9М (2М каталог + 7М поиск)
2. [x] количество трансляций в день ровно дневному пику, так быть не может
3. [x] пиковый трафик посчитан неверно, если умнощить 2Мбит/с на 2,5 млн пиковый онлайн число другое
4. [x] непонятно как отправленные сообщения и чем метод доставки отличаются от доставки количества зрителей стрима
5. [x] вам нужно где-то хранить потоковый буфер и считать по нему нагрузку и размер
6. [x] физическая схема БД нужна картинкой
8. [x] на таких объемах стримов сервис от AWS может быть очень дорогим
9. [x] нужно продумать решение для топовых стримов, может не хватить производительности одного шарта

**Comment by p1xelse** [comment]
1) Многие пользователи сразу заходят на страницу из любимого стримера, поэтому добавил пункт - страница стримера
2-3) не понял в каком пункте это 
4) Счетчик количества зрителей обновляется раз в минуту, а сообщения появляются в лайве, сообщения можно через WS организовать
5) Добавил храниение в Nginx RTMP
6) Поправил
7) Чуть запутался, я вот сейчас добавил Nginx RTMP, у него как я нагуглил не так много функционала как у AWS, но кажется, что можно обойтись без AWS, оставил только Nginx RTMP. По идее они могут работать и в связке, но это кажется лишним. 
8) Одного шарда для хранения потокового буфера? Если да, то я думаю можно как-то поиграться с Nginx RTMP

**Comment by init** [comment]
1. принято
2) у вас дневной максимум трансляций 107К и столько же всего трансляций в день, не все трансляции пересекаются о времени пункт, "Среднее количество действий пользователей"
3) пункт "Технические метрики"
2. инкремент/декремент счетчика можно также как сообщения передавать, зачем вам 2 разных способа для одного и того же
3. нет в логической и физической схеме, непонятно почему нужно хранить суточный объем, нет оценки нагрузки в iops / bytes/s
4. пока не понимаю как работают у вас счетчики

**Comment by p1xelse** [comment]
2) поправил
5)  RTMP
6) картинка
7) вот nginx rtmp и aws запутался
